pipeline {
    agent any

    environment {
        TF_VAR_s3_bkt_name = "${params.S3_BUCKET_NAME}"
        TF_VAR_dynamo_tbl_name = "${params.DYNAMO_TABLE_NAME}"
    }


    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('checkout') {
            steps {
                git branch: 'jenkinstest', url: 'https://github.com/navinrdyy/terraform-zero-to-hero.git'
                
            }
        }

        stage('Build') {
            steps {
                sh 'cd Day-4/prereq && terraform init && terraform plan'
                
            }
        }

        
    }
}